set(CPACK_PACKAGE_NAME "EvenementLoto")
if (${PROJECT_PREFIX}_PACKAGE_NAME) # to be defined in presets
    set(CPACK_PACKAGE_NAME "${${PROJECT_PREFIX}_PACKAGE_NAME}")
endif ()
set(CPACK_PACKAGE_VENDOR "${${PROJECT_PREFIX}_AUTHOR}")
set(CPACK_PACKAGE_VERSION_MAJOR ${CMAKE_PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${CMAKE_PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${CMAKE_PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
# Get the latest abbreviated commit hash of the working branch

if (${PROJECT_PREFIX}_DISTRIBUTION)
    set(${PROJECT_PREFIX}_OS_VERSION "${${PROJECT_PREFIX}_DISTRIBUTION}")
else ()
    if (${PROJECT_PREFIX}_PLATFORM_ANDROID)
        set(${PROJECT_PREFIX}_OS_VERSION "${CMAKE_SYSTEM_VERSION}")
    elseif (${PROJECT_PREFIX}_PLATFORM_IOS OR ${PROJECT_PREFIX}_PLATFORM_MACOS)
        set(${PROJECT_PREFIX}_OS_VERSION "${CMAKE_OSX_DEPLOYMENT_TARGET}")
    endif ()
endif ()

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${${PROJECT_PREFIX}_PLATFORM_STR}-${${PROJECT_PREFIX}_ARCH_STR}")
message(STATUS "PACKAGING Expected package Name: ${CPACK_PACKAGE_FILE_NAME}")

if (${PROJECT_PREFIX}_PLATFORM_WINDOWS)
    set(CPACK_GENERATOR "ZIP")
else ()
    set(CPACK_GENERATOR "TGZ")
endif ()

message(STATUS "Using ${CPACK_GENERATOR} Package generator")
