
find_program(EDEPMANAGER depmanager)
if (${EDEPMANAGER} STREQUAL EDEPMANAGER-NOTFOUND)
    message(FATAL_ERROR "Dependency manager not found.")
else ()
    execute_process(COMMAND ${EDEPMANAGER} info cmakedir
            OUTPUT_VARIABLE depmanager_path)
    execute_process(COMMAND ${EDEPMANAGER} info version
            OUTPUT_VARIABLE depmanager_version)
    message(STATUS "Depmanager found: version ${depmanager_version}")
    string(STRIP ${depmanager_path} depmanager_path)
    string(REPLACE "\\" "/" depmanager_path ${depmanager_path})
    list(PREPEND CMAKE_MODULE_PATH ${depmanager_path})
    include(DepManager)
endif ()

message(STATUS "Loading third parties with Depmanager...")
dm_load_environment(KIND shared)
message(STATUS "Third parties loaded.")
message(STATUS "-----------------------------------")
message(STATUS "CMAKE_PREFIX_PATH:")
foreach (path IN LISTS CMAKE_PREFIX_PATH)
    if (path STREQUAL "")
        continue ()
    endif ()
    message(STATUS "  - ${path}")
endforeach ()
message(STATUS "CMAKE_MODULE_PATH:")
foreach (path IN LISTS CMAKE_MODULE_PATH)
    if (path STREQUAL "")
        continue ()
    endif ()
    message(STATUS "  - ${path}")
endforeach ()
message(STATUS "-----------------------------------")
