
find_program(EDEPMANAGER depmanager)
if (${EDEPMANAGER} STREQUAL EDEPMANAGER-NOTFOUND)
    message(FATAL_ERROR "Dependency manager not found.")
else ()
    execute_process(COMMAND ${EDEPMANAGER} info version --raw
            OUTPUT_VARIABLE depmanager_version)
    string(STRIP ${depmanager_version} depmanager_version)
    string(REPLACE "depmanager" "" depmanager_version ${depmanager_version})
    string(REPLACE "version" "" depmanager_version ${depmanager_version})
    string(STRIP ${depmanager_version} depmanager_version)
    message(STATUS "Depmanager found: ${EDEPMANAGER} version ${depmanager_version}")

    execute_process(COMMAND ${EDEPMANAGER} info cmakedir --raw
            OUTPUT_VARIABLE depmanager_cmake_dir)
    string(STRIP ${depmanager_cmake_dir} depmanager_cmake_dir)
    string(REPLACE "\\" "/" depmanager_cmake_dir ${depmanager_cmake_dir})
    string(REPLACE "\n" "" depmanager_cmake_dir ${depmanager_cmake_dir})
    string(REPLACE "\r" "" depmanager_cmake_dir ${depmanager_cmake_dir})
    message(STATUS "Depmanager cmake modules path: ${depmanager_cmake_dir}")
    if (NOT EXISTS ${depmanager_cmake_dir}/DepManager.cmake)
        message(FATAL_ERROR "Depmanager cmake modules not found at: ${depmanager_cmake_dir}")
    endif ()

    list(PREPEND CMAKE_MODULE_PATH ${depmanager_cmake_dir})
    include(DepManager)
endif ()

message(STATUS "Loading third parties with Depmanager...")
dm_load_environment(KIND shared)
message(STATUS "Third parties loaded.")
message(STATUS "-----------------------------------")
message(STATUS "CMAKE_PREFIX_PATH:")
foreach (path IN LISTS CMAKE_PREFIX_PATH)
    if (path STREQUAL "")
        continue ()
    endif ()
    message(STATUS "  - ${path}")
endforeach ()
message(STATUS "CMAKE_MODULE_PATH:")
foreach (path IN LISTS CMAKE_MODULE_PATH)
    if (path STREQUAL "")
        continue ()
    endif ()
    message(STATUS "  - ${path}")
endforeach ()
message(STATUS "-----------------------------------")
